#!/bin/sh

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

wm="xmonad"

sh ~/.xprofile

xrdb ~/.xresources

compton --config ~/.config/compton.conf -b &

nm-applet &

systemctl --user restart redshift.service

feh --bg-fill ~/Immagini/HLD_Screenshot_01_camp_1080.png

xfce4-power-manager &

iceweasel &

#greenclip daemon &

# (sleep 5; conky -b -c ~/.conkyrc) &

#owncloud &
telegram-desktop &

if [ "$wm" = "xmonad" ]; then
    #stalonetray &
    polybar example &

    # set the default cursor
    xsetroot -cursor_name left_ptr

    ( sleep 10; conky -b -c ~/.conky/conkyrc ) &
    ( sleep 10; conky -b -c ~/.conky/conky_mpd ) &

    termite -t toxic --class=toxic --name=toxic -e toxic &
    termite -t ncmpcpp --class=ncmpcpp --name=ncmpcpp -e ncmpcpp &
    termite -t weechat --class=weechat --name=weechat -e weechat &
    termite -t ranger --class=ranger --name=ranger -e ranger &

    exec ~/.local/bin/xmonad
else
    exec i3
fi

# exec awesome
#exec i3
#exec xmonad
#twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login
