#!/bin/python

import subprocess
import re
import datetime

def get_output(cmd):
    return subprocess.check_output(cmd).decode("utf-8")

def tmux_get_sname():
    return get_output(['tmux', 'display-message', '-p', '#S']).replace('\n', '')

def get_song_formatted(max):
    mpd = get_output(['mpc']).split('\n')
    if re.match('\[playing\]', mpd[1]):
        if len(mpd[0]) <= max :
            return mpd[0]
        else:
            return mpd[0][0:(max-3)] + "..."
    else:
        return "paused"

sname = tmux_get_sname()

status = "#[fg=colour16]at #[fg=green]"
status += sname
status += "#[fg=blue] playing #[fg=colour5]"
status += get_song_formatted(38 - len(sname))
status += "#[fg=colour16] ~ #[fg=colour23]"
status += datetime.datetime.today().strftime('%d %b %Y %H:%M')

print(status)
