#!/bin/sh

cd ~/build

for i in $(ls -d */); do
    cd $i

    printf "\n\n"
    printf '\e[1;34m%-6s\e[m' "Updating \"${i%%/}\""
    printf "\n\n"

#    git remote update >> /dev/null
#    git merge origin/master >> /dev/null
    # si: create a new package
    #  f: owerwrite existing package
#     git pull --dry-run | grep -q -v 'Already up-to-date.' && makepkg -sif
    makepkg -scif

    cd ..
done

# clean orpan packages
sudo pacman -R $(pacman -Qdtq)
