typeset -U path

# VARS
export VISUAL="kak"
export EDITOR="kak"
export FZF_DEFAULT_COMMAND='ag -g ""'
export MANPAGER="nvim -c 'set ft=man' -"
export PAGER="/usr/bin/less"
export LESS="-iMr"
export BROWSER="w3m"
export GOPATH=~/go


path=(
    ~/.node_modules/bin
    ~/.config/composer/vendor/bin
    ~/.local/bin/
    $(ruby -e 'print Gem.user_dir')/bin
    $GOPATH/bin
    $path[@]
    )

source ~/.cargo/env

