typeset -U path

path=(
    ~/.local/bin/
    $(ruby -e 'print Gem.user_dir')/bin
    $path[@]
    )

source ~/.cargo/env

# VARS
export VISUAL="vim"
export EDITOR="vim"
export FZF_DEFAULT_COMMAND='ag -g ""'
export MANPAGER="nvim -c 'set ft=man' -"
export PAGER="/usr/bin/less"
export LESS="-iMr"

