# Path to your oh-my-zsh installation.
export ZSH=/home/omar/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
# ZSH_THEME="agnoster" # (this is one of the fancy ones)
# ZSH_THEME="avit" # (this is one of the fancy ones)
# ZSH_THEME="af-magic"
#ZSH_THEME="wezm"
ZSH_THEME="honukai"
DEFAULT_USER="omar"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git gitignore symfony2)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.node_modules/bin:$HOME/.local/bin:$(ruby -e 'print Gem.user_dir')/bin"
# export MANPATH="/usr/local/man:$MANPATH"
#
export CLASSPATH="$HOME/bin/bsh-2.0b4.jar"

source $ZSH/oh-my-zsh.sh

export NVM_DIR="/home/omar/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm use stable --silent

export VISUAL="nvim"
export EDITOR="nvim"

# export npm_config_prefix=~/.node_modules

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias enw="emacs -nw"
alias nvimrc="v ~/.config/nvim/init.vim"
alias composer="php ~/bin/composer.phar"
alias google="elinks www.google.com"
alias vim="nvim"
alias v="nvim"
alias e="elinks"
alias exit_statuses="cat $(find /usr -name sysexits.h -print -quit) | less"
alias zshrc="v ~/.zshrc"
alias bsh="java bsh.Interpreter"

# list of animals I like
animals=(cower tux eyes default koala small moose moofasa bong vader-koala elephant)

# the length
animals_length=$(echo $animals[(I)$animals[-1]])

# random number
rnd=$(awk -v min=1 -v max=$animals_length 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')

# lets rock!
command cowthink -f $animals[$rnd] $(fortune -s)

# che mi aiuti a togliere il delay quando premo <Esc>?
KEYTIMEOUT=1
